const fs = require('fs');
const h = fs.readFileSync('index.html', 'utf8');
const c = fs.readFileSync('style.css', 'utf8');
console.log('Video bg in hero:', h.includes('<video class="hero-bg-layer"'));
console.log('Video src correct:', h.includes('bg-video.mp4'));
console.log('Old bg-image removed:', !h.includes('background-image'));
console.log('CTA buttons kept:', h.includes('btn-shop-luxury') && h.includes('btn-vip-gold'));
console.log('hero-bg-layer contain:', c.includes('object-fit: contain') && c.includes('.hero-bg-layer'));
console.log('heroSlowZoom removed:', !c.includes('heroSlowZoom'));
console.log('mens-new title present:', c.includes('.saelyx-mens-new-title'));
console.log('CSS braces balanced:', (c.match(/{/g) || []).length === (c.match(/}/g) || []).length);
